{
  "uid" : "7b73436404c79fa4",
  "name" : "test_2",
  "fullName" : "test_sample#test_2",
  "historyId" : "bcf5c0b3b21ee411ee5a11e7417fbe6b",
  "time" : {
    "start" : 1639039723982,
    "stop" : 1639039723982,
    "duration" : 0
  },
  "description" : "这是测试谷歌搜索",
  "descriptionHtml" : "<p>这是测试谷歌搜索</p>\n",
  "status" : "broken",
  "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\Admin\\\\Desktop\\\\Personal\\\\python\\\\test/config/env_config.yml'",
  "statusTrace" : "request = <SubRequest 'env' for <Function test_1>>\n\n    @pytest.fixture(scope=\"session\", autouse=True)\n    def env(request):\n        \"\"\"\n        Parse env config info\n        \"\"\"\n        root_dir = request.config.rootdir\n        config_path = '{0}/config/env_config.yml'.format(root_dir)\n>       with open(config_path) as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\Admin\\\\Desktop\\\\Personal\\\\python\\\\test/config/env_config.yml'\n\nconftest.py:15: FileNotFoundError",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 1,
  "retriesStatusChange" : false,
  "beforeStages" : [ {
    "name" : "env",
    "time" : {
      "start" : 1639039723930,
      "stop" : 1639039723930,
      "duration" : 0
    },
    "status" : "broken",
    "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\Admin\\\\Desktop\\\\Personal\\\\python\\\\test/config/env_config.yml'\n",
    "statusTrace" : "  File \"C:\\software\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\software\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\software\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Admin\\Desktop\\Personal\\python\\test\\conftest.py\", line 15, in env\n    with open(config_path) as f:\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : true,
    "attachmentsCount" : 0,
    "stepsCount" : 0,
    "hasContent" : true
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "story",
    "value" : "谷歌搜索"
  }, {
    "name" : "suite",
    "value" : "test_sample"
  }, {
    "name" : "host",
    "value" : "LAPTOP-KBI1AOOR"
  }, {
    "name" : "thread",
    "value" : "21124-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_sample"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "749a3da167c8dfb",
      "status" : "broken",
      "statusDetails" : "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\Admin\\\\Desktop\\\\Personal\\\\python\\\\test/config/env_config.yml'",
      "time" : {
        "start" : 1639039701425,
        "stop" : 1639039701425,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "7b73436404c79fa4.json",
  "parameterValues" : [ ]
}